name: portfolio
description: "My portfolio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.1  
  firebase_storage: ^12.1.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.1
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  dio: ^5.4.3+1
  web: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:

  uses-material-design: true
  assets:
    - assets/splash/
    - assets/main/
    - assets/home/
    - assets/about/
    - assets/work/
    - assets/contact/




